# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/devcontainer-playground',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/devcontainer-playground',
                'lib_path': 'devcontainer_playground'},
  'syms': {'devcontainer_playground.core': {'devcontainer_playground.core.foo': ('core.html#foo', 'devcontainer_playground/core.py')}}}
